CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHusersAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULTusers CURRENT_TIMESTAMP
);